### PR TITLE
Csv import

### PR DESCRIPTION
**Pull request by caewok**
This code revamps csv_to_disk.frame. Specifically addresses #199, and helps with #9. 

Basic idea: User has two options. (1) split csv files in advance using split_csv_file and then read the files using csv_to_disk.frame. (2) read csv files in chunks using csv_to_disk.frame. In either case, the default chunks for the resulting disk.frame will be equal to the number of infiles, plus any spilt infiles due to chunking. Importing of multiple csv files is done in parallel, based on future.  By breaking this into two options, the code is simplified because the number of chunking methods is decreased, and thus the combination of chunking and backend method are decreased. This works really well when, for example, you are importing from an already partitioned set of csv files as one would expect to find using Spark. 

csv_to_disk.frame can now guess at the number of desired chunks using exported function estimate_chunks_needed. csv_to_disk.frame can also guess at the column types, and will try to create compatible column types if they vary across infiles. For example, if csv_file 1 has an integer column, but csv_file 2 includes numerics in that integer column, csv_to_disk.frame can set the column to numeric for both files. 

The basic methodology is as follows: user can call split_csv_file if desired. Then user calls  csv_to_disk.frame. If nchunks is not specified, then file sizes are checked (estimate_chunks_needed) and files are chunked if necessary. Each file or each file chunk is saved to an fst file in the outfile directory. Then disk.frame is called to create the disk.frame from the saved fst files. This limits copies of fst or csv files. 

For now, shardby is disabled. The initial implementation is meant to use shardby at the end, but this causes errors:
For shardby_function = "hash", Error: `path` must be a directory, in rechunk function
For shardby_function = "sort",  Error in rechunk(df, shardby = shardby, nchunks = nchunks_rechunk, outdir = outdir,  nchunks must be larger than 1 .

It would seem that the disk.frame function is not setting something in the metadata that in turn is causing the shard function to become confused. If I figure out what it is, I will try to update disk.frame or shard accordingly.

Long term, I would expect sharding to happen a bit earlier, as the chunks are saved. Instead of saving each chunk, we could instead save each shard of the chunk, appending the fst file as additional chunks are processed. This would save time in that the resulting disk.frame would not need to be re-sharded and re-chunked at the end. I see that the fst package intends to implement appending fst files at a later date.

### CODE REVIEW

**Comment by xiaodaigh** [comment]
Thank you. I will review. The part about shard by not work must be addressed. I will review and respond on further actions.

Also as a general rule, please make sure the branch pass CRAN check as well. You can find the code to run CRAN check in https://github.com/xiaodaigh/disk.frame/blob/master/utils/build_utils.R 

Just runt he code `df_check()`

**Comment by caewok** [comment]
Yeah, the df_check() function reverted the changes I made to the vignette, which causes it to fail the check. The intro-disk-frame needs to reflect the new csv_to_disk.frame function, and in particular, pass an inchunks parameter. It looks like maybe you are copying the vignettes from elsewhere using df_check(), so the original vignette file should be modified instead?
    On Sunday, November 10, 2019, 05:54:14 PM PST, evalparse <notifications@github.com> wrote:  
 
 
Thank you. I will review. The part about shard by not work must be addressed. I will review and respond on further actions.

Also as a general rule, please make sure the branch pass CRAN check as well. You can find the code to run CRAN check in https://github.com/xiaodaigh/disk.frame/blob/master/utils/build_utils.R

Just runt he code df_check()

**Comment by xiaodaigh** [comment]
Yes. The original vignette are in book. Please update. We need to make sure
nothing breaks. Thanks

**Comment by xiaodaigh** [comment]
@caewok  Can you please make this PR against the development branch? Instead of the master branch? Thanks

**Comment by xiaodaigh** [comment]
I will close this. If picked up again in future. Please re-open.

**Pull request closed without merging**
